# Best Accuracy Model for Deployment (Tugas UAS)

## Read-Me !


> Tugas UAS, Cari model terbaik dari dataset yang dipakai dalam website berikut

---


▶ Kunjungi [Website](https://muhammadkurniasani2342.pythonanywhere.com/)


**❗ Aturan**


* 👉  Ambil [data set](https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset)
* 👉  Lakukan *preproccessing*
* 👉  Lakukan *split* data latih & data tes
* 👉  Hitung *accuracy* dengan setiap model berikut
**  Gaussian Naive Bayes
**  Linier Regression
**  Random Forest
**  Decision Tree
**  KNN
* 👉  Cari model dengan *accuracy* terbaik





### Import Library

In [25]:
### Data Wrangling 
import pandas as pd
import numpy as np
from scipy.io import arff

### Modelling 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

### Remove unnecessary warnings
import warnings
warnings.filterwarnings('ignore')

### Load Data

In [26]:
# Create dataset from Google Drive
dataset_url = "/content/drive/MyDrive/datamining/tugas/notebooks-assignement/asset/Dry_Bean_Dataset.arff"
data = arff.loadarff(dataset_url)

In [27]:
df = pd.DataFrame(data[0])

In [28]:
print(df.shape)

(13611, 17)


In [29]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             13611 non-null  float64
 1   Perimeter        13611 non-null  float64
 2   MajorAxisLength  13611 non-null  float64
 3   MinorAxisLength  13611 non-null  float64
 4   AspectRation     13611 non-null  float64
 5   Eccentricity     13611 non-null  float64
 6   ConvexArea       13611 non-null  float64
 7   EquivDiameter    13611 non-null  float64
 8   Extent           13611 non-null  float64
 9   Solidity         13611 non-null  float64
 10  roundness        13611 non-null  float64
 11  Compactness      13611 non-null  float64
 12  ShapeFactor1     13611 non-null  float64
 13  ShapeFactor2     13611 non-null  float64
 14  ShapeFactor3     13611 non-null  float64
 15  ShapeFactor4     13611 non-null  float64
 16  Class            13611 non-null  object 
dtypes: float64(1

In [30]:
df.head(10)

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395.0    610.291       208.178117       173.888747      1.197191   
1  28734.0    638.018       200.524796       182.734419      1.097356   
2  29380.0    624.110       212.826130       175.931143      1.209713   
3  30008.0    645.884       210.557999       182.516516      1.153638   
4  30140.0    620.134       201.847882       190.279279      1.060798   
5  30279.0    634.927       212.560556       181.510182      1.171067   
6  30477.0    670.033       211.050155       184.039050      1.146768   
7  30519.0    629.727       212.996755       182.737204      1.165591   
8  30685.0    635.681       213.534145       183.157146      1.165852   
9  30834.0    631.934       217.227813       180.897469      1.200834   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812     28715.0     190.141097  0.763923  0.988856   0.958027   
1      0.411785     29172.0     191.272750  0.783968  0.984986   0.887034   
2      0.562727     29690.0     193.410904  0.778113  0.989559   0.947849   
3      0.498616     30724.0     195.467062  0.782681  0.976696   0.903936   
4      0.333680     30417.0     195.896503  0.773098  0.990893   0.984877   
5      0.520401     30600.0     196.347702  0.775688  0.989510   0.943852   
6      0.489478     30970.0     196.988633  0.762402  0.984081   0.853080   
7      0.513760     30847.0     197.124320  0.770682  0.989367   0.967109   
8      0.514081     31044.0     197.659696  0.771561  0.988436   0.954240   
9      0.553642     31120.0     198.139012  0.783683  0.990810   0.970278   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0     0.913358      0.007332      0.003147      0.834222      0.998724   
1     0.953861      0.006979      0.003564      0.909851      0.998430   
2     0.908774      0.007244      0.003048      0.825871      0.999066   
3     0.928329      0.007017      0.003215      0.861794      0.994199   
4     0.970516      0.006697      0.003665      0.941900      0.999166   
5     0.923726      0.007020      0.003153      0.853270      0.999236   
6     0.933374      0.006925      0.003242      0.871186      0.999049   
7     0.925480      0.006979      0.003158      0.856514      0.998345   
8     0.925658      0.006959      0.003152      0.856844      0.998953   
9     0.912125      0.007045      0.003008      0.831973      0.999061   

      Class  
0  b'SEKER'  
1  b'SEKER'  
2  b'SEKER'  
3  b'SEKER'  
4  b'SEKER'  
5  b'SEKER'  
6  b'SEKER'  
7  b'SEKER'  
8  b'SEKER'  
9  b'SEKER'

### Preproccessing Data

In [67]:
### CONSTANT
FIRST_IDX = 0

#### Split Data Class & Data Value

In [31]:
X = df.drop(columns=["Class"])

In [68]:
print(X)

[[-0.84074853 -1.1433189  -1.30659814 ...  2.40217287  1.92572347
   0.83837103]
 [-0.82918764 -1.01392388 -1.39591111 ...  3.10089314  2.68970162
   0.77113842]
 [-0.80715717 -1.07882906 -1.25235661 ...  2.23509147  1.84135576
   0.91675514]
 ...
 [-0.37203825 -0.44783294 -0.45047814 ...  0.28920441  0.33632829
   0.39025114]
 [-0.37176543 -0.42702856 -0.42897404 ...  0.22837538  0.2489734
   0.03644001]
 [-0.37135619 -0.38755718 -0.2917356  ... -0.12777587 -0.2764814
   0.71371948]]


In [33]:
y = df['Class'].values

In [69]:
print(y)

[5 5 5 ... 3 3 3]


In [57]:
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)

In [70]:
print(y)

[5 5 5 ... 3 3 3]


#### Normalization

In [36]:
scaler = preprocessing.StandardScaler().fit(X)

In [37]:
X = scaler.transform(X)

In [71]:
print(X[FIRST_IDX])

[-0.84074853 -1.1433189  -1.30659814 -0.63115304 -1.56505251 -2.18572039
 -0.84145059 -1.0633406   0.28908744  0.36761343  1.42386707  1.8391164
  0.68078638  2.40217287  1.92572347  0.83837103]


#### Split Train Data & Test Data

In [39]:
amount_of_test_data_in_percent = 0.3

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=amount_of_test_data_in_percent, random_state=123)

In [65]:
print(y_train)

[2 0 0 ... 5 3 1]


#### Define Decision Tree Models

In [42]:
# membuat model Decision Tree
tree_model = DecisionTreeClassifier()

In [43]:
# Melatih model dengan menggunakan data latih
tree_model = tree_model.fit(X_train, y_train)

#### Model Evaluation


In [44]:
y_pred = tree_model.predict(X_test)

In [45]:
acc_secore = round(accuracy_score(y_pred, y_test), 3)

In [46]:
print('Accuracy: ', acc_secore)

Accuracy:  0.895


#### Model Predict 

**Attributes**


*   Perimeter
*   MajorAxisLength
*   MinorAxisLength
*   AspectRation
*   Eccentricity
*   ConvexArea
*   EquivDiameter
*   Extent
*   Solidity
*   roundness
*   Compactness
*   ShapeFactor1
*   ShapeFactor2
*   ShapeFactor3
*   ShapeFactor4


```
# Values
[
    -0.84074853,
    -1.1433189 ,
    -1.30659814,
    -0.63115304,
    -1.56505251,
    -2.18572039,
    -0.84145059,
    -1.0633406 ,
    0.28908744,
    0.36761343,
    1.42386707,
    1.8391164 ,
    0.68078638,
    2.40217287,
    1.92572347,
    0.83837103
]
```



In [56]:
# prediksi model dengan tree_model.predict([[SepalLength, SepalWidth, PetalLength, PetalWidth]])
print(tree_model.predict([[
        -0.84074853, -1.1433189, -1.30659814, -0.63115304, -1.56505251,
        -2.18572039, -0.84145059, -1.0633406,  0.28908744,  0.36761343,
        1.42386707,  1.8391164 ,  0.68078638,  2.40217287,  1.92572347, 
        0.83837103]]
))

[5]
